# Generated by Django 5.2.6 on 2025-09-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Название"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Город"),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Подпись"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Email",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Подпись"
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContactTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Тема обращения",
                "verbose_name_plural": "Темы обращений",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactWorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekdays", models.CharField(max_length=200, verbose_name="Будни")),
                ("saturday", models.CharField(max_length=200, verbose_name="Суббота")),
                (
                    "sunday",
                    models.CharField(max_length=200, verbose_name="Воскресенье"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Режим работы",
                "verbose_name_plural": "Режим работы",
            },
        ),
        migrations.AlterModelOptions(
            name="advantage",
            options={
                "ordering": ["ordering", "id"],
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.AlterModelOptions(
            name="carouselitem",
            options={
                "ordering": ["ordering", "-id"],
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="companyinfo",
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.AlterModelOptions(
            name="metric",
            options={
                "ordering": ["ordering", "id"],
                "verbose_name": "Показатель",
                "verbose_name_plural": "Показатели",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["ordering", "id"],
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товара",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["ordering", "id"],
                "verbose_name": "Член команды",
                "verbose_name_plural": "Команда",
            },
        ),
        migrations.AlterModelOptions(
            name="value",
            options={
                "ordering": ["ordering", "id"],
                "verbose_name": "Ценность",
                "verbose_name_plural": "Ценности",
            },
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="main_catego_slug_f935f9_idx",
            old_name="main_categ_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="main_produc_slug_354b31_idx",
            old_name="main_produ_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="main_produc_is_acti_723717_idx",
            old_name="main_produ_is_act_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="main_produc_categor_9c4415_idx",
            old_name="main_produ_category_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="main_produc_created_276cd8_idx",
            old_name="main_produ_created_idx",
        ),
        migrations.RenameIndex(
            model_name="productimage",
            new_name="main_produc_product_9452e5_idx",
            old_name="main_prod_product_37e421_idx",
        ),
        migrations.AlterField(
            model_name="advantage",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="about/icons/", verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активно"
            ),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="advantage",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="image",
            field=models.ImageField(upload_to="carousel/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активен"
            ),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="link_url",
            field=models.URLField(blank=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Подзаголовок"
            ),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="about_text",
            field=models.TextField(blank=True, verbose_name="О компании"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="contacts",
            field=models.JSONField(blank=True, null=True, verbose_name="Контакты"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="mission_text",
            field=models.TextField(blank=True, verbose_name="Миссия"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активно"
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="suffix",
            field=models.CharField(blank=True, max_length=20, verbose_name="Суффикс"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="value",
            field=models.CharField(max_length=60, verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активен"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=180, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Альтернативный текст"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Основное"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активен"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(upload_to="about/team/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(max_length=120, verbose_name="Роль"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="short_bio",
            field=models.TextField(blank=True, verbose_name="Краткая биография"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="social_links",
            field=models.JSONField(blank=True, null=True, verbose_name="Соцсети"),
        ),
        migrations.AlterField(
            model_name="value",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="value",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="about/values/", verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активно"
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="main.contacttopic",
                verbose_name="Тема",
            ),
        ),
    ]
