# Generated by Django 5.2.6 on 2025-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contactaddress_contactemail_contactphone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                (
                    "map_embed",
                    models.TextField(
                        blank=True, verbose_name="Карта (встраиваемый код)"
                    ),
                ),
                (
                    "map_url",
                    models.URLField(blank=True, verbose_name="Ссылка на карту"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Соцсети и карта",
                "verbose_name_plural": "Соцсети и карта",
            },
        ),
    ]
