# Generated by Django 5.2.6 on 2025-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_socialmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_main",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Показывать на главной"
            ),
        ),
    ]
