# Generated by Django 5.2.6 on 2025-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_product_is_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("home", "Главная"), ("about", "О нас")],
                        max_length=10,
                        verbose_name="Страница",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/",
                        verbose_name="Видео-файл",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="YouTube ссылка"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
                "ordering": ("order", "-created_at"),
            },
        ),
    ]
