# Generated by Django 5.1.6 on 2025-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmap',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='Whatsapp'),
        ),
    ]
