# Generated by Django 5.2.6 on 2025-09-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_socialmap_tiktok_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Фон для блока, можно не добавлять",
                        null=True,
                        upload_to="section_headers/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Ключ страницы: catalog, about, contact и т.д.",
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Заголовок секции",
                "verbose_name_plural": "Заголовки секций",
            },
        ),
    ]
