# Generated by ChatGPT
from django.db import migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_sectionheader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField("Описание", blank=True),
        ),
    ]
