# Generated by Django 5.1.6 on 2025-09-23 10:22

import ckeditor.fields
import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_multilingual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Преимущество Translation'},
        ),
        migrations.AlterModelOptions(
            name='carouselitemtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Слайд Translation'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Категория Translation'},
        ),
        migrations.AlterModelOptions(
            name='companyinfotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Информация о компании Translation'},
        ),
        migrations.AlterModelOptions(
            name='contactaddresstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Адрес Translation'},
        ),
        migrations.AlterModelOptions(
            name='contactemailtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Email Translation'},
        ),
        migrations.AlterModelOptions(
            name='contactphonetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Телефон Translation'},
        ),
        migrations.AlterModelOptions(
            name='contacttopic',
            options={'ordering': ['slug'], 'verbose_name': 'Тема обращения', 'verbose_name_plural': 'Темы обращений'},
        ),
        migrations.AlterModelOptions(
            name='contacttopictranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Тема обращения Translation'},
        ),
        migrations.AlterModelOptions(
            name='contactworkinghourstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Режим работы Translation'},
        ),
        migrations.AlterModelOptions(
            name='metrictranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Показатель Translation'},
        ),
        migrations.AlterModelOptions(
            name='productimagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Изображение товара Translation'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Товар Translation'},
        ),
        migrations.AlterModelOptions(
            name='sectionheadertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Заголовок секции Translation'},
        ),
        migrations.AlterModelOptions(
            name='teammembertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Член команды Translation'},
        ),
        migrations.AlterModelOptions(
            name='valuetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Ценность Translation'},
        ),
        migrations.AlterModelOptions(
            name='videotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Видео Translation'},
        ),
        migrations.AlterField(
            model_name='advantagetranslation',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advantagetranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advantagetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='advantagetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.advantage'),
        ),
        migrations.AlterField(
            model_name='advantagetranslation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='carouselitemtranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carouselitemtranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='carouselitemtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.carouselitem'),
        ),
        migrations.AlterField(
            model_name='carouselitemtranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='carouselitemtranslation',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.category'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companyinfotranslation',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='companyinfotranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyinfotranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='companyinfotranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.companyinfo'),
        ),
        migrations.AlterField(
            model_name='companyinfotranslation',
            name='mission_text',
            field=models.TextField(blank=True, verbose_name='Миссия'),
        ),
        migrations.AlterField(
            model_name='contactaddresstranslation',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactaddresstranslation',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contactaddresstranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactaddresstranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contactaddresstranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.contactaddress'),
        ),
        migrations.AlterField(
            model_name='contactaddresstranslation',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contactemailtranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactemailtranslation',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='contactemailtranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contactemailtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.contactemail'),
        ),
        migrations.AlterField(
            model_name='contactphonetranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactphonetranslation',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='contactphonetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contactphonetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.contactphone'),
        ),
        migrations.AlterField(
            model_name='contacttopictranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contacttopictranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contacttopictranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.contacttopic'),
        ),
        migrations.AlterField(
            model_name='contacttopictranslation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.contactworkinghours'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='saturday',
            field=models.CharField(max_length=200, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='sunday',
            field=models.CharField(max_length=200, verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='contactworkinghourstranslation',
            name='weekdays',
            field=models.CharField(max_length=200, verbose_name='Будни'),
        ),
        migrations.AlterField(
            model_name='metrictranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metrictranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='metrictranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.metric'),
        ),
        migrations.AlterField(
            model_name='metrictranslation',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='metrictranslation',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Суффикс'),
        ),
        migrations.AlterField(
            model_name='metrictranslation',
            name='value',
            field=models.CharField(max_length=60, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.productimage'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.product'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sectionheadertranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sectionheadertranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionheadertranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='sectionheadertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.sectionheader'),
        ),
        migrations.AlterField(
            model_name='sectionheadertranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.teammember'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='role',
            field=models.CharField(max_length=120, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='short_bio',
            field=models.TextField(blank=True, verbose_name='Краткая биография'),
        ),
        migrations.AlterField(
            model_name='valuetranslation',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='valuetranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='valuetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='valuetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.value'),
        ),
        migrations.AlterField(
            model_name='valuetranslation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='videotranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videotranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='videotranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.video'),
        ),
        migrations.AlterField(
            model_name='videotranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
